### ISSUE TITLE
HI,about the project.

### ISSUE THREAD

**Issue by tangyudi** [dpaiton/deep-style#3]
Thank you for sharing you code.I have some questions.

1.I want to know if I use your caffe and run deeptest.py then I can get the result? I do not find the code about the PyDataLayer.
2.Can you tell me how fast is your project?

**Comment by dpaiton** [comment]
Hello, you will have to build my branch of caffe, from this link: https://github.com/dpaiton/caffe/tree/gramian

Once you have done this you can run deepstyle.py to generate images.

It is faster than a strict python implementation, but slower than the current TensorFlow implementations.
